#!/usr/bin/env ruby

POSTS = "posts"
SITE = "site"
ORIGINAL_EXT = ".text"

require 'liquid'
require 'kramdown'

@post_template = Liquid::Template.parse(File.open("post.html").read.gsub(/href=\"(.*)\"/,'href="../\1"'))

posts_dir = Dir.open(File.join(Dir.pwd, POSTS))

posts_dir.each do |filename|
  post_file = File.open(File.join(posts_dir.path, filename))
  if File::file? post_file
    post_page = @post_template.render('post' => Kramdown::Document.new(post_file.read).to_html)
    puts filename
    post_html = File.open(File.join(SITE, File.basename(filename, ORIGINAL_EXT)) + ".html", "w+")
    post_html.write(post_page)
    post_html.close
  end
end
