#!/usr/bin/env ruby

POSTS = "posts"
SITE = "site"
ORIGINAL_EXT = ".text"

require 'liquid'
require 'kramdown'
require 'yaml'

YAML::ENGINE.yamler = 'psych'

@post_template = Liquid::Template.parse(File.open("post.html").read.gsub(/href=\"(.*)\"/,'href="../\1"'))

posts_dir = Dir.open(File.join(Dir.pwd, POSTS))

@posts = Array.new

posts_dir.each do |filename|
  post_file = File.open(File.join(posts_dir.path, filename))
  if File::file? post_file
    metadata, content = post_file.read.partition("\n---")
    values = YAML::load(metadata)
    values["content"] = Kramdown::Document.new(content).to_html
    scoped_values = Hash.new
    values.to_hash.each do |key, value|
      scoped_values["post." + key] = value
    end
#    @posts << post
    post_page = @post_template.render(scoped_values)
    puts filename
    post_html = File.open(File.join(SITE, File.basename(filename, ORIGINAL_EXT)) + ".html", "w+")
    post_html.write(post_page)
    post_html.close
  end
end
